theme: minima

author:
  name: Diwank Tomer
  email: "diwank.singh@gmail.com"

minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/8factor-agent/methodology" }
    - { platform: x, user_url: "https://x.com/diwanksingh" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/diwank-tomer" }
    # bluesky
    # codeberg
    # devto
    # dribbble
    # facebook
    # flickr
    # gitlab
    # google_scholar
    # instagram
    # keybase
    # mastodon
    # microdotblog
    # pinterest
    # stackoverflow
    # telegram
    # whatsapp
    # youtube

# header_pages:
#   - about.md
#   - portfolio.md

show_excerpts: true
